# Generated by Django 5.2 on 2025-04-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('leak_repair', 'Leak Repair'), ('pipe_installation', 'Pipe Installation'), ('drain_cleaning', 'Drain Cleaning'), ('emergency_plumbing', 'Emergency Plumbing')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
